// Code generated by the Lingua Franca compiler from:
// file://Users/kyankotschevar-smead/Desktop/Projects/Embedded-Systems/lab1/src/ToolsLEDSolution.lf
#define LOG_LEVEL 2

#include <limits.h>
#include "low_level_platform/api/low_level_platform.h"
#include "include/api/schedule.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(void) {
   return lf_reactor_c_main(0, NULL);
}
void lf_set_default_command_line_options() {}
#include "_led.h"
#include "_toolsledsolution_main.h"
typedef enum {
    toolsledsolution_main,
    num_environments
} _enclave_id;
// The global array of environments associated with each enclave
static environment_t environments[num_environments];
// 'Create' and initialize the environments in the program
void lf_create_environments() {
    environment_init(&environments[toolsledsolution_main],"toolsledsolution_main",toolsledsolution_main,_lf_number_of_workers,1,1,0,0,1,0,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) environments;
   return num_environments;
}
// Arrays representing the enclaves downstream of `toolsledsolution_main_downstream`
#define TOOLSLEDSOLUTION_MAIN_NUM_DOWNSTREAM 0
// No downstreams, but 0-length arrays not allowed by MSVC (C2466)
int toolsledsolution_main_downstream[1] = {-1};
// Arrays representing the enclaves upstream of `toolsledsolution_main_upstream`
#define TOOLSLEDSOLUTION_MAIN_NUM_UPSTREAM 0
// No upstreams, but 0-length arrays not allowed by MSVC (C2466)
int toolsledsolution_main_upstream[1] = {-1};
// No upstreams, but 0-length arrays not allowed by MSVC (C2466)
interval_t toolsledsolution_main_upstream_delay[1] = {FOREVER};
// Writes a pointer to the array of upstream enclaves into `result` and returns the length
int lf_get_upstream_of(int enclave_id, int ** result) {
    int num_upstream;
    int* upstream;
    switch(enclave_id) { 
        case toolsledsolution_main:
            num_upstream = TOOLSLEDSOLUTION_MAIN_NUM_UPSTREAM;
            upstream = &toolsledsolution_main_upstream[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = upstream;
    return num_upstream;
}
// Writes a pointer to the array of downstream enclaves into `result` and returns the length
int lf_get_downstream_of(int enclave_id, int ** result) {
    int num_downstream;
    int* downstream;
    switch(enclave_id) { 
        case toolsledsolution_main:
            num_downstream = TOOLSLEDSOLUTION_MAIN_NUM_DOWNSTREAM;
            downstream = &toolsledsolution_main_downstream[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = downstream;
    return num_downstream;
}
// Writes a pointer to the array of upstream delays into `result` and returns the length
int lf_get_upstream_delay_of(int enclave_id, interval_t ** result) {
    int num_upstream;
    interval_t* delay;
    switch(enclave_id) { 
        case toolsledsolution_main:
            num_upstream = TOOLSLEDSOLUTION_MAIN_NUM_UPSTREAM;
            delay = &toolsledsolution_main_upstream_delay[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = delay;
    return num_upstream;
}
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int watchdog_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(watchdog_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _toolsledsolution_main_main_self_t* toolsledsolution_main_self[1];
    SUPPRESS_UNUSED_WARNING(toolsledsolution_main_self);
    _led_self_t* toolsledsolution_led_self[1];
    SUPPRESS_UNUSED_WARNING(toolsledsolution_led_self);
    // ***** Start initializing ToolsLEDSolution of class ToolsLEDSolution
    toolsledsolution_main_self[0] = new__toolsledsolution_main();
    toolsledsolution_main_self[0]->base.environment = &environments[toolsledsolution_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    { // For scoping
        static bool _initial = false;
        toolsledsolution_main_self[0]->led_on = _initial;
    } // End scoping.
    { // For scoping
        static int _initial = 0;
        toolsledsolution_main_self[0]->blink_count = _initial;
    } // End scoping.
    { // For scoping
        static int _initial = 1;
        toolsledsolution_main_self[0]->target_blinks = _initial;
    } // End scoping.
    { // For scoping
        static bool _initial = false;
        toolsledsolution_main_self[0]->in_pause = _initial;
    } // End scoping.
    { // For scoping
        static int _initial = 0;
        toolsledsolution_main_self[0]->pause_ticks = _initial;
    } // End scoping.
    // Initiaizing timer ToolsLEDSolution.t.
    toolsledsolution_main_self[0]->_lf__t.offset = SEC(1);
    toolsledsolution_main_self[0]->_lf__t.period = MSEC(100);
    // Associate timer with the environment of its parent
    environments[toolsledsolution_main].timer_triggers[timer_triggers_count[toolsledsolution_main]++] = &toolsledsolution_main_self[0]->_lf__t;
    toolsledsolution_main_self[0]->_lf__t.mode = NULL;
    
    toolsledsolution_main_self[0]->_lf__reaction_0.deadline = NEVER;
    #if !defined LF_SINGLE_THREADED
    toolsledsolution_main_self[0]->base.reactor_mutex = NULL;
    #endif
    {
        _toolsledsolution_main_main_self_t *self = toolsledsolution_main_self[0];
        // ***** Start initializing ToolsLEDSolution.led of class LED
        toolsledsolution_led_self[0] = new__led();
        toolsledsolution_led_self[0]->base.environment = &environments[toolsledsolution_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        toolsledsolution_led_self[0]->_lf_set_width = -2;
        environments[toolsledsolution_main].startup_reactions[startup_reaction_count[toolsledsolution_main]++] = &toolsledsolution_led_self[0]->_lf__reaction_0;
    
        toolsledsolution_led_self[0]->_lf__reaction_0.deadline = NEVER;
        toolsledsolution_led_self[0]->_lf__reaction_1.deadline = NEVER;
        #if !defined LF_SINGLE_THREADED
        toolsledsolution_led_self[0]->base.reactor_mutex = NULL;
        #endif
        //***** End initializing ToolsLEDSolution.led
    }
    //***** End initializing ToolsLEDSolution
    // **** Start deferred initialize for ToolsLEDSolution
    {
        toolsledsolution_main_self[0]->base.name = "ToolsLEDSolution";
        toolsledsolution_main_self[0]->base.parent = (self_base_t*)NULL;
    
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of ToolsLEDSolution.
        toolsledsolution_main_self[0]->_lf__reaction_0.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        toolsledsolution_main_self[0]->_lf__reaction_0.triggers = (trigger_t***)lf_allocate(
                1, sizeof(trigger_t**),
                &toolsledsolution_main_self[0]->base.allocations);
        toolsledsolution_main_self[0]->_lf__reaction_0.triggered_sizes = (int*)lf_allocate(
                1, sizeof(int),
                &toolsledsolution_main_self[0]->base.allocations);
        toolsledsolution_main_self[0]->_lf__reaction_0.output_produced = (bool**)lf_allocate(
                1, sizeof(bool*),
                &toolsledsolution_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                toolsledsolution_main_self[0]->_lf__reaction_0.output_produced[count++] = &toolsledsolution_main_self[0]->_lf_led.set.is_present;
            }
        }
        
        // ** End initialization for reaction 0 of ToolsLEDSolution
    
        // **** Start deferred initialize for ToolsLEDSolution.led
        {
            toolsledsolution_led_self[0]->base.name = "led";
            toolsledsolution_led_self[0]->base.parent = (self_base_t*)toolsledsolution_main_self[0];
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of ToolsLEDSolution.led.
            toolsledsolution_led_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of ToolsLEDSolution.led
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of ToolsLEDSolution.led.
            toolsledsolution_led_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of ToolsLEDSolution.led
        
        }
        // **** End of deferred initialize for ToolsLEDSolution.led
    }
    // **** End of deferred initialize for ToolsLEDSolution
    // **** Start non-nested deferred initialize for ToolsLEDSolution
    {
        // Set number of destination reactors for port led.set.
        // Iterate over range ToolsLEDSolution.led.set(0,1)->[ToolsLEDSolution.led.set(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            toolsledsolution_main_self[src_runtime]->_lf_led.set._base.num_destinations = 1;
            toolsledsolution_main_self[src_runtime]->_lf_led.set._base.source_reactor = (self_base_t*)toolsledsolution_main_self[src_runtime];
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range ToolsLEDSolution.led.set(0,1)->[ToolsLEDSolution.led.set(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 0 of ToolsLEDSolution triggers 1 downstream reactions
                // through port ToolsLEDSolution.led.set.
                toolsledsolution_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 0 of ToolsLEDSolution, allocate an
                // array of trigger pointers for downstream reactions through port ToolsLEDSolution.led.set
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &toolsledsolution_main_self[src_runtime]->base.allocations); 
                toolsledsolution_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges ToolsLEDSolution.led.set(0,1)->[ToolsLEDSolution.led.set(0,1)] and ToolsLEDSolution.led.set(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range ToolsLEDSolution.led.set(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port ToolsLEDSolution.led.set's trigger struct.
                    toolsledsolution_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &toolsledsolution_led_self[dst_runtime]->_lf__set;
                }
            }
        }
    
        // **** Start non-nested deferred initialize for ToolsLEDSolution.led
        {
        
        
        
        
        }
        // **** End of non-nested deferred initialize for ToolsLEDSolution.led
    }
    // **** End of non-nested deferred initialize for ToolsLEDSolution
    // Connect inputs and outputs for reactor ToolsLEDSolution.
    // Connect inputs and outputs for reactor ToolsLEDSolution.led.
    // Connect ToolsLEDSolution.led.set(0,1)->[ToolsLEDSolution.led.set(0,1)] to port ToolsLEDSolution.led.set(0,1)
    // Iterate over ranges ToolsLEDSolution.led.set(0,1)->[ToolsLEDSolution.led.set(0,1)] and ToolsLEDSolution.led.set(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range ToolsLEDSolution.led.set(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            toolsledsolution_led_self[dst_runtime]->_lf_set = (_led_set_t*)&toolsledsolution_main_self[src_runtime]->_lf_led.set;
        }
    }
    {
    }
    // Add port ToolsLEDSolution.led.set to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                environments[toolsledsolution_main].is_present_fields[0 + (0) * 1 + count] = &toolsledsolution_main_self[0]->_lf_led.set.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                environments[toolsledsolution_main]._lf_intended_tag_fields[0 + (0) * 1 + count] = &toolsledsolution_main_self[0]->_lf_led.set.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    
    // Set reaction priorities for ReactorInstance ToolsLEDSolution
    {
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        toolsledsolution_main_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
    
        // Set reaction priorities for ReactorInstance ToolsLEDSolution.led
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            toolsledsolution_led_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            toolsledsolution_led_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 1);
        }
    
    }
    

    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&environments[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
 #ifdef FEDERATED_CENTRALIZED
     lf_latest_tag_confirmed(tag_to_send);
 #else
     (void) tag_to_send;
 #endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void lf_terminate_execution(environment_t* env) {
    (void) env;
}
#endif
