// Code generated by the Lingua Franca compiler from:
// file://home/masonmenser/Embedded-Systems/lab2/AccelerometerDisplay.lf
#define LOG_LEVEL 2

#include <limits.h>
#include "low_level_platform/api/low_level_platform.h"
#include "include/api/schedule.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(void) {
   return lf_reactor_c_main(0, NULL);
}
void lf_set_default_command_line_options() {}
#include "_accelerometer.h"
#include "_display.h"
#include "_accelerometerdisplay_main.h"
typedef enum {
    accelerometerdisplay_main,
    num_environments
} _enclave_id;
// The global array of environments associated with each enclave
static environment_t environments[num_environments];
// 'Create' and initialize the environments in the program
void lf_create_environments() {
    environment_init(&environments[accelerometerdisplay_main],"accelerometerdisplay_main",accelerometerdisplay_main,_lf_number_of_workers,1,2,0,0,7,0,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) environments;
   return num_environments;
}
// Arrays representing the enclaves downstream of `accelerometerdisplay_main_downstream`
#define ACCELEROMETERDISPLAY_MAIN_NUM_DOWNSTREAM 0
// No downstreams, but 0-length arrays not allowed by MSVC (C2466)
int accelerometerdisplay_main_downstream[1] = {-1};
// Arrays representing the enclaves upstream of `accelerometerdisplay_main_upstream`
#define ACCELEROMETERDISPLAY_MAIN_NUM_UPSTREAM 0
// No upstreams, but 0-length arrays not allowed by MSVC (C2466)
int accelerometerdisplay_main_upstream[1] = {-1};
// No upstreams, but 0-length arrays not allowed by MSVC (C2466)
interval_t accelerometerdisplay_main_upstream_delay[1] = {FOREVER};
// Writes a pointer to the array of upstream enclaves into `result` and returns the length
int lf_get_upstream_of(int enclave_id, int ** result) {
    int num_upstream;
    int* upstream;
    switch(enclave_id) { 
        case accelerometerdisplay_main:
            num_upstream = ACCELEROMETERDISPLAY_MAIN_NUM_UPSTREAM;
            upstream = &accelerometerdisplay_main_upstream[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = upstream;
    return num_upstream;
}
// Writes a pointer to the array of downstream enclaves into `result` and returns the length
int lf_get_downstream_of(int enclave_id, int ** result) {
    int num_downstream;
    int* downstream;
    switch(enclave_id) { 
        case accelerometerdisplay_main:
            num_downstream = ACCELEROMETERDISPLAY_MAIN_NUM_DOWNSTREAM;
            downstream = &accelerometerdisplay_main_downstream[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = downstream;
    return num_downstream;
}
// Writes a pointer to the array of upstream delays into `result` and returns the length
int lf_get_upstream_delay_of(int enclave_id, interval_t ** result) {
    int num_upstream;
    interval_t* delay;
    switch(enclave_id) { 
        case accelerometerdisplay_main:
            num_upstream = ACCELEROMETERDISPLAY_MAIN_NUM_UPSTREAM;
            delay = &accelerometerdisplay_main_upstream_delay[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = delay;
    return num_upstream;
}
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int watchdog_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(watchdog_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _accelerometerdisplay_main_main_self_t* accelerometerdisplay_main_self[1];
    SUPPRESS_UNUSED_WARNING(accelerometerdisplay_main_self);
    _accelerometer_self_t* accelerometerdisplay_a_self[1];
    SUPPRESS_UNUSED_WARNING(accelerometerdisplay_a_self);
    _display_self_t* accelerometerdisplay_d_self[1];
    SUPPRESS_UNUSED_WARNING(accelerometerdisplay_d_self);
    // ***** Start initializing AccelerometerDisplay of class AccelerometerDisplay
    accelerometerdisplay_main_self[0] = new__accelerometerdisplay_main();
    accelerometerdisplay_main_self[0]->base.environment = &environments[accelerometerdisplay_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    // Initiaizing timer AccelerometerDisplay.t.
    accelerometerdisplay_main_self[0]->_lf__t.offset = 0;
    accelerometerdisplay_main_self[0]->_lf__t.period = MSEC(250);
    // Associate timer with the environment of its parent
    environments[accelerometerdisplay_main].timer_triggers[timer_triggers_count[accelerometerdisplay_main]++] = &accelerometerdisplay_main_self[0]->_lf__t;
    accelerometerdisplay_main_self[0]->_lf__t.mode = NULL;
    
    accelerometerdisplay_main_self[0]->_lf__reaction_0.deadline = NEVER;
    accelerometerdisplay_main_self[0]->_lf__reaction_1.deadline = NEVER;
    #if !defined LF_SINGLE_THREADED
    accelerometerdisplay_main_self[0]->base.reactor_mutex = NULL;
    #endif
    {
        _accelerometerdisplay_main_main_self_t *self = accelerometerdisplay_main_self[0];
        // ***** Start initializing AccelerometerDisplay.a of class Accelerometer
        accelerometerdisplay_a_self[0] = new__accelerometer();
        accelerometerdisplay_a_self[0]->base.environment = &environments[accelerometerdisplay_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        
        
        // width of -2 indicates that it is not a multiport.
        accelerometerdisplay_a_self[0]->_lf_x_width = -2;
        
        
        // width of -2 indicates that it is not a multiport.
        accelerometerdisplay_a_self[0]->_lf_y_width = -2;
        
        
        // width of -2 indicates that it is not a multiport.
        accelerometerdisplay_a_self[0]->_lf_z_width = -2;
        // width of -2 indicates that it is not a multiport.
        accelerometerdisplay_a_self[0]->_lf_trigger_width = -2;
        environments[accelerometerdisplay_main].startup_reactions[startup_reaction_count[accelerometerdisplay_main]++] = &accelerometerdisplay_a_self[0]->_lf__reaction_0;
    
        accelerometerdisplay_a_self[0]->_lf__reaction_0.deadline = NEVER;
        accelerometerdisplay_a_self[0]->_lf__reaction_1.deadline = NEVER;
        #if !defined LF_SINGLE_THREADED
        accelerometerdisplay_a_self[0]->base.reactor_mutex = NULL;
        #endif
        //***** End initializing AccelerometerDisplay.a
    }
    {
        _accelerometerdisplay_main_main_self_t *self = accelerometerdisplay_main_self[0];
        // ***** Start initializing AccelerometerDisplay.d of class Display
        accelerometerdisplay_d_self[0] = new__display();
        accelerometerdisplay_d_self[0]->base.environment = &environments[accelerometerdisplay_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        accelerometerdisplay_d_self[0]->_lf_line0_width = -2;
        // width of -2 indicates that it is not a multiport.
        accelerometerdisplay_d_self[0]->_lf_line1_width = -2;
        // width of -2 indicates that it is not a multiport.
        accelerometerdisplay_d_self[0]->_lf_line2_width = -2;
        // width of -2 indicates that it is not a multiport.
        accelerometerdisplay_d_self[0]->_lf_line3_width = -2;
        environments[accelerometerdisplay_main].startup_reactions[startup_reaction_count[accelerometerdisplay_main]++] = &accelerometerdisplay_d_self[0]->_lf__reaction_0;
    
        accelerometerdisplay_d_self[0]->_lf__reaction_0.deadline = NEVER;
        accelerometerdisplay_d_self[0]->_lf__reaction_1.deadline = NEVER;
        #if !defined LF_SINGLE_THREADED
        accelerometerdisplay_d_self[0]->base.reactor_mutex = NULL;
        #endif
        //***** End initializing AccelerometerDisplay.d
    }
    //***** End initializing AccelerometerDisplay
    // **** Start deferred initialize for AccelerometerDisplay
    {
        accelerometerdisplay_main_self[0]->base.name = "AccelerometerDisplay";
        accelerometerdisplay_main_self[0]->base.parent = (self_base_t*)NULL;
    
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of AccelerometerDisplay.
        accelerometerdisplay_main_self[0]->_lf__reaction_0.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        accelerometerdisplay_main_self[0]->_lf__reaction_0.triggers = (trigger_t***)lf_allocate(
                1, sizeof(trigger_t**),
                &accelerometerdisplay_main_self[0]->base.allocations);
        accelerometerdisplay_main_self[0]->_lf__reaction_0.triggered_sizes = (int*)lf_allocate(
                1, sizeof(int),
                &accelerometerdisplay_main_self[0]->base.allocations);
        accelerometerdisplay_main_self[0]->_lf__reaction_0.output_produced = (bool**)lf_allocate(
                1, sizeof(bool*),
                &accelerometerdisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                accelerometerdisplay_main_self[0]->_lf__reaction_0.output_produced[count++] = &accelerometerdisplay_main_self[0]->_lf_a.trigger.is_present;
            }
        }
        
        // ** End initialization for reaction 0 of AccelerometerDisplay
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_2 of AccelerometerDisplay.
        accelerometerdisplay_main_self[0]->_lf__reaction_1.num_outputs = 3;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        accelerometerdisplay_main_self[0]->_lf__reaction_1.triggers = (trigger_t***)lf_allocate(
                3, sizeof(trigger_t**),
                &accelerometerdisplay_main_self[0]->base.allocations);
        accelerometerdisplay_main_self[0]->_lf__reaction_1.triggered_sizes = (int*)lf_allocate(
                3, sizeof(int),
                &accelerometerdisplay_main_self[0]->base.allocations);
        accelerometerdisplay_main_self[0]->_lf__reaction_1.output_produced = (bool**)lf_allocate(
                3, sizeof(bool*),
                &accelerometerdisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                accelerometerdisplay_main_self[0]->_lf__reaction_1.output_produced[count++] = &accelerometerdisplay_main_self[0]->_lf_d.line0.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                accelerometerdisplay_main_self[0]->_lf__reaction_1.output_produced[count++] = &accelerometerdisplay_main_self[0]->_lf_d.line1.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                accelerometerdisplay_main_self[0]->_lf__reaction_1.output_produced[count++] = &accelerometerdisplay_main_self[0]->_lf_d.line2.is_present;
            }
        }
        
        // ** End initialization for reaction 1 of AccelerometerDisplay
    
        // **** Start deferred initialize for AccelerometerDisplay.a
        {
            accelerometerdisplay_a_self[0]->base.name = "a";
            accelerometerdisplay_a_self[0]->base.parent = (self_base_t*)accelerometerdisplay_main_self[0];
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of AccelerometerDisplay.a.
            accelerometerdisplay_a_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of AccelerometerDisplay.a
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of AccelerometerDisplay.a.
            accelerometerdisplay_a_self[0]->_lf__reaction_1.num_outputs = 3;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            accelerometerdisplay_a_self[0]->_lf__reaction_1.triggers = (trigger_t***)lf_allocate(
                    3, sizeof(trigger_t**),
                    &accelerometerdisplay_a_self[0]->base.allocations);
            accelerometerdisplay_a_self[0]->_lf__reaction_1.triggered_sizes = (int*)lf_allocate(
                    3, sizeof(int),
                    &accelerometerdisplay_a_self[0]->base.allocations);
            accelerometerdisplay_a_self[0]->_lf__reaction_1.output_produced = (bool**)lf_allocate(
                    3, sizeof(bool*),
                    &accelerometerdisplay_a_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    accelerometerdisplay_a_self[0]->_lf__reaction_1.output_produced[count++] = &accelerometerdisplay_a_self[0]->_lf_x.is_present;
                }
                {
                    accelerometerdisplay_a_self[0]->_lf__reaction_1.output_produced[count++] = &accelerometerdisplay_a_self[0]->_lf_y.is_present;
                }
                {
                    accelerometerdisplay_a_self[0]->_lf__reaction_1.output_produced[count++] = &accelerometerdisplay_a_self[0]->_lf_z.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of AccelerometerDisplay.a
        
        }
        // **** End of deferred initialize for AccelerometerDisplay.a
        // **** Start deferred initialize for AccelerometerDisplay.d
        {
            accelerometerdisplay_d_self[0]->base.name = "d";
            accelerometerdisplay_d_self[0]->base.parent = (self_base_t*)accelerometerdisplay_main_self[0];
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of AccelerometerDisplay.d.
            accelerometerdisplay_d_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of AccelerometerDisplay.d
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of AccelerometerDisplay.d.
            accelerometerdisplay_d_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of AccelerometerDisplay.d
        
        }
        // **** End of deferred initialize for AccelerometerDisplay.d
    }
    // **** End of deferred initialize for AccelerometerDisplay
    // **** Start non-nested deferred initialize for AccelerometerDisplay
    {
        // Set number of destination reactors for port a.trigger.
        // Iterate over range AccelerometerDisplay.a.trigger(0,1)->[AccelerometerDisplay.a.trigger(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            accelerometerdisplay_main_self[src_runtime]->_lf_a.trigger._base.num_destinations = 1;
            accelerometerdisplay_main_self[src_runtime]->_lf_a.trigger._base.source_reactor = (self_base_t*)accelerometerdisplay_main_self[src_runtime];
        }
        // Set number of destination reactors for port d.line0.
        // Iterate over range AccelerometerDisplay.d.line0(0,1)->[AccelerometerDisplay.d.line0(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            accelerometerdisplay_main_self[src_runtime]->_lf_d.line0._base.num_destinations = 1;
            accelerometerdisplay_main_self[src_runtime]->_lf_d.line0._base.source_reactor = (self_base_t*)accelerometerdisplay_main_self[src_runtime];
        }
        // Set number of destination reactors for port d.line1.
        // Iterate over range AccelerometerDisplay.d.line1(0,1)->[AccelerometerDisplay.d.line1(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            accelerometerdisplay_main_self[src_runtime]->_lf_d.line1._base.num_destinations = 1;
            accelerometerdisplay_main_self[src_runtime]->_lf_d.line1._base.source_reactor = (self_base_t*)accelerometerdisplay_main_self[src_runtime];
        }
        // Set number of destination reactors for port d.line2.
        // Iterate over range AccelerometerDisplay.d.line2(0,1)->[AccelerometerDisplay.d.line2(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            accelerometerdisplay_main_self[src_runtime]->_lf_d.line2._base.num_destinations = 1;
            accelerometerdisplay_main_self[src_runtime]->_lf_d.line2._base.source_reactor = (self_base_t*)accelerometerdisplay_main_self[src_runtime];
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range AccelerometerDisplay.a.trigger(0,1)->[AccelerometerDisplay.a.trigger(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 0 of AccelerometerDisplay triggers 1 downstream reactions
                // through port AccelerometerDisplay.a.trigger.
                accelerometerdisplay_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 0 of AccelerometerDisplay, allocate an
                // array of trigger pointers for downstream reactions through port AccelerometerDisplay.a.trigger
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &accelerometerdisplay_main_self[src_runtime]->base.allocations); 
                accelerometerdisplay_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges AccelerometerDisplay.a.trigger(0,1)->[AccelerometerDisplay.a.trigger(0,1)] and AccelerometerDisplay.a.trigger(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range AccelerometerDisplay.a.trigger(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port AccelerometerDisplay.a.trigger's trigger struct.
                    accelerometerdisplay_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &accelerometerdisplay_a_self[dst_runtime]->_lf__trigger;
                }
            }
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range AccelerometerDisplay.d.line0(0,1)->[AccelerometerDisplay.d.line0(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 1 of AccelerometerDisplay triggers 1 downstream reactions
                // through port AccelerometerDisplay.d.line0.
                accelerometerdisplay_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 1 of AccelerometerDisplay, allocate an
                // array of trigger pointers for downstream reactions through port AccelerometerDisplay.d.line0
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &accelerometerdisplay_main_self[src_runtime]->base.allocations); 
                accelerometerdisplay_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            // Iterate over range AccelerometerDisplay.d.line1(0,1)->[AccelerometerDisplay.d.line1(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 1 of AccelerometerDisplay triggers 1 downstream reactions
                // through port AccelerometerDisplay.d.line1.
                accelerometerdisplay_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 1 of AccelerometerDisplay, allocate an
                // array of trigger pointers for downstream reactions through port AccelerometerDisplay.d.line1
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &accelerometerdisplay_main_self[src_runtime]->base.allocations); 
                accelerometerdisplay_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            // Iterate over range AccelerometerDisplay.d.line2(0,1)->[AccelerometerDisplay.d.line2(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 1 of AccelerometerDisplay triggers 1 downstream reactions
                // through port AccelerometerDisplay.d.line2.
                accelerometerdisplay_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 1 of AccelerometerDisplay, allocate an
                // array of trigger pointers for downstream reactions through port AccelerometerDisplay.d.line2
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &accelerometerdisplay_main_self[src_runtime]->base.allocations); 
                accelerometerdisplay_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges AccelerometerDisplay.d.line0(0,1)->[AccelerometerDisplay.d.line0(0,1)] and AccelerometerDisplay.d.line0(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range AccelerometerDisplay.d.line0(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port AccelerometerDisplay.d.line0's trigger struct.
                    accelerometerdisplay_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &accelerometerdisplay_d_self[dst_runtime]->_lf__line0;
                }
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 1;
            // Iterate over ranges AccelerometerDisplay.d.line1(0,1)->[AccelerometerDisplay.d.line1(0,1)] and AccelerometerDisplay.d.line1(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range AccelerometerDisplay.d.line1(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port AccelerometerDisplay.d.line1's trigger struct.
                    accelerometerdisplay_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &accelerometerdisplay_d_self[dst_runtime]->_lf__line1;
                }
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 2;
            // Iterate over ranges AccelerometerDisplay.d.line2(0,1)->[AccelerometerDisplay.d.line2(0,1)] and AccelerometerDisplay.d.line2(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range AccelerometerDisplay.d.line2(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port AccelerometerDisplay.d.line2's trigger struct.
                    accelerometerdisplay_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &accelerometerdisplay_d_self[dst_runtime]->_lf__line2;
                }
            }
        }
    
        // **** Start non-nested deferred initialize for AccelerometerDisplay.a
        {
        
            // For reference counting, set num_destinations for port AccelerometerDisplay.a.x.
            // Iterate over range AccelerometerDisplay.a.x(0,1)->[AccelerometerDisplay.a.x(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                accelerometerdisplay_a_self[src_runtime]->_lf_x._base.num_destinations = 1;
                accelerometerdisplay_a_self[src_runtime]->_lf_x._base.source_reactor = (self_base_t*)accelerometerdisplay_a_self[src_runtime];
            }
            // For reference counting, set num_destinations for port AccelerometerDisplay.a.y.
            // Iterate over range AccelerometerDisplay.a.y(0,1)->[AccelerometerDisplay.a.y(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                accelerometerdisplay_a_self[src_runtime]->_lf_y._base.num_destinations = 1;
                accelerometerdisplay_a_self[src_runtime]->_lf_y._base.source_reactor = (self_base_t*)accelerometerdisplay_a_self[src_runtime];
            }
            // For reference counting, set num_destinations for port AccelerometerDisplay.a.z.
            // Iterate over range AccelerometerDisplay.a.z(0,1)->[AccelerometerDisplay.a.z(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                accelerometerdisplay_a_self[src_runtime]->_lf_z._base.num_destinations = 1;
                accelerometerdisplay_a_self[src_runtime]->_lf_z._base.source_reactor = (self_base_t*)accelerometerdisplay_a_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range AccelerometerDisplay.a.x(0,1)->[AccelerometerDisplay.a.x(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 1 of AccelerometerDisplay.a triggers 1 downstream reactions
                    // through port AccelerometerDisplay.a.x.
                    accelerometerdisplay_a_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 1 of AccelerometerDisplay.a, allocate an
                    // array of trigger pointers for downstream reactions through port AccelerometerDisplay.a.x
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &accelerometerdisplay_a_self[src_runtime]->base.allocations); 
                    accelerometerdisplay_a_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                // Iterate over range AccelerometerDisplay.a.y(0,1)->[AccelerometerDisplay.a.y(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 1 of AccelerometerDisplay.a triggers 1 downstream reactions
                    // through port AccelerometerDisplay.a.y.
                    accelerometerdisplay_a_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 1 of AccelerometerDisplay.a, allocate an
                    // array of trigger pointers for downstream reactions through port AccelerometerDisplay.a.y
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &accelerometerdisplay_a_self[src_runtime]->base.allocations); 
                    accelerometerdisplay_a_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                // Iterate over range AccelerometerDisplay.a.z(0,1)->[AccelerometerDisplay.a.z(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 1 of AccelerometerDisplay.a triggers 1 downstream reactions
                    // through port AccelerometerDisplay.a.z.
                    accelerometerdisplay_a_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 1 of AccelerometerDisplay.a, allocate an
                    // array of trigger pointers for downstream reactions through port AccelerometerDisplay.a.z
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &accelerometerdisplay_a_self[src_runtime]->base.allocations); 
                    accelerometerdisplay_a_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges AccelerometerDisplay.a.x(0,1)->[AccelerometerDisplay.a.x(0,1)] and AccelerometerDisplay.a.x(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range AccelerometerDisplay.a.x(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Port AccelerometerDisplay.a.x has reactions in its parent's parent.
                        // Point to the trigger struct for those reactions.
                        accelerometerdisplay_a_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &accelerometerdisplay_main_self[dst_runtime]->_lf_a.x_trigger;
                    }
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 1;
                // Iterate over ranges AccelerometerDisplay.a.y(0,1)->[AccelerometerDisplay.a.y(0,1)] and AccelerometerDisplay.a.y(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range AccelerometerDisplay.a.y(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Port AccelerometerDisplay.a.y has reactions in its parent's parent.
                        // Point to the trigger struct for those reactions.
                        accelerometerdisplay_a_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &accelerometerdisplay_main_self[dst_runtime]->_lf_a.y_trigger;
                    }
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 2;
                // Iterate over ranges AccelerometerDisplay.a.z(0,1)->[AccelerometerDisplay.a.z(0,1)] and AccelerometerDisplay.a.z(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range AccelerometerDisplay.a.z(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Port AccelerometerDisplay.a.z has reactions in its parent's parent.
                        // Point to the trigger struct for those reactions.
                        accelerometerdisplay_a_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &accelerometerdisplay_main_self[dst_runtime]->_lf_a.z_trigger;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for AccelerometerDisplay.a
        // **** Start non-nested deferred initialize for AccelerometerDisplay.d
        {
        
        
        
        
        }
        // **** End of non-nested deferred initialize for AccelerometerDisplay.d
    }
    // **** End of non-nested deferred initialize for AccelerometerDisplay
    // Connect inputs and outputs for reactor AccelerometerDisplay.
    // Connect inputs and outputs for reactor AccelerometerDisplay.a.
    // Connect AccelerometerDisplay.a.trigger(0,1)->[AccelerometerDisplay.a.trigger(0,1)] to port AccelerometerDisplay.a.trigger(0,1)
    // Iterate over ranges AccelerometerDisplay.a.trigger(0,1)->[AccelerometerDisplay.a.trigger(0,1)] and AccelerometerDisplay.a.trigger(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range AccelerometerDisplay.a.trigger(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            accelerometerdisplay_a_self[dst_runtime]->_lf_trigger = (_accelerometer_trigger_t*)&accelerometerdisplay_main_self[src_runtime]->_lf_a.trigger;
        }
    }
    // Connect AccelerometerDisplay.a.x(0,1)->[AccelerometerDisplay.a.x(0,1)] to port AccelerometerDisplay.a.x(0,1)
    // Iterate over ranges AccelerometerDisplay.a.x(0,1)->[AccelerometerDisplay.a.x(0,1)] and AccelerometerDisplay.a.x(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range AccelerometerDisplay.a.x(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            accelerometerdisplay_main_self[dst_runtime]->_lf_a.x = (_accelerometer_x_t*)&accelerometerdisplay_a_self[src_runtime]->_lf_x;
        }
    }
    // Connect AccelerometerDisplay.a.y(0,1)->[AccelerometerDisplay.a.y(0,1)] to port AccelerometerDisplay.a.y(0,1)
    // Iterate over ranges AccelerometerDisplay.a.y(0,1)->[AccelerometerDisplay.a.y(0,1)] and AccelerometerDisplay.a.y(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range AccelerometerDisplay.a.y(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            accelerometerdisplay_main_self[dst_runtime]->_lf_a.y = (_accelerometer_y_t*)&accelerometerdisplay_a_self[src_runtime]->_lf_y;
        }
    }
    // Connect AccelerometerDisplay.a.z(0,1)->[AccelerometerDisplay.a.z(0,1)] to port AccelerometerDisplay.a.z(0,1)
    // Iterate over ranges AccelerometerDisplay.a.z(0,1)->[AccelerometerDisplay.a.z(0,1)] and AccelerometerDisplay.a.z(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range AccelerometerDisplay.a.z(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            accelerometerdisplay_main_self[dst_runtime]->_lf_a.z = (_accelerometer_z_t*)&accelerometerdisplay_a_self[src_runtime]->_lf_z;
        }
    }
    // Connect inputs and outputs for reactor AccelerometerDisplay.d.
    // Connect AccelerometerDisplay.d.line0(0,1)->[AccelerometerDisplay.d.line0(0,1)] to port AccelerometerDisplay.d.line0(0,1)
    // Iterate over ranges AccelerometerDisplay.d.line0(0,1)->[AccelerometerDisplay.d.line0(0,1)] and AccelerometerDisplay.d.line0(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range AccelerometerDisplay.d.line0(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            accelerometerdisplay_d_self[dst_runtime]->_lf_line0 = (_display_line0_t*)&accelerometerdisplay_main_self[src_runtime]->_lf_d.line0;
        }
    }
    // Connect AccelerometerDisplay.d.line1(0,1)->[AccelerometerDisplay.d.line1(0,1)] to port AccelerometerDisplay.d.line1(0,1)
    // Iterate over ranges AccelerometerDisplay.d.line1(0,1)->[AccelerometerDisplay.d.line1(0,1)] and AccelerometerDisplay.d.line1(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range AccelerometerDisplay.d.line1(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            accelerometerdisplay_d_self[dst_runtime]->_lf_line1 = (_display_line1_t*)&accelerometerdisplay_main_self[src_runtime]->_lf_d.line1;
        }
    }
    // Connect AccelerometerDisplay.d.line2(0,1)->[AccelerometerDisplay.d.line2(0,1)] to port AccelerometerDisplay.d.line2(0,1)
    // Iterate over ranges AccelerometerDisplay.d.line2(0,1)->[AccelerometerDisplay.d.line2(0,1)] and AccelerometerDisplay.d.line2(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range AccelerometerDisplay.d.line2(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            accelerometerdisplay_d_self[dst_runtime]->_lf_line2 = (_display_line2_t*)&accelerometerdisplay_main_self[src_runtime]->_lf_d.line2;
        }
    }
    {
    }
    {
    }
    // Add port AccelerometerDisplay.a.trigger to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                environments[accelerometerdisplay_main].is_present_fields[0 + (0) * 1 + count] = &accelerometerdisplay_main_self[0]->_lf_a.trigger.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                environments[accelerometerdisplay_main]._lf_intended_tag_fields[0 + (0) * 1 + count] = &accelerometerdisplay_main_self[0]->_lf_a.trigger.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port AccelerometerDisplay.d.line0 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                environments[accelerometerdisplay_main].is_present_fields[1 + (0) * 1 + count] = &accelerometerdisplay_main_self[0]->_lf_d.line0.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                environments[accelerometerdisplay_main]._lf_intended_tag_fields[1 + (0) * 1 + count] = &accelerometerdisplay_main_self[0]->_lf_d.line0.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port AccelerometerDisplay.d.line1 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                environments[accelerometerdisplay_main].is_present_fields[2 + (0) * 1 + count] = &accelerometerdisplay_main_self[0]->_lf_d.line1.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                environments[accelerometerdisplay_main]._lf_intended_tag_fields[2 + (0) * 1 + count] = &accelerometerdisplay_main_self[0]->_lf_d.line1.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port AccelerometerDisplay.d.line2 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                environments[accelerometerdisplay_main].is_present_fields[3 + (0) * 1 + count] = &accelerometerdisplay_main_self[0]->_lf_d.line2.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                environments[accelerometerdisplay_main]._lf_intended_tag_fields[3 + (0) * 1 + count] = &accelerometerdisplay_main_self[0]->_lf_d.line2.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add output port AccelerometerDisplay.a.x to array of is_present fields.
            environments[accelerometerdisplay_main].is_present_fields[(0) * 3 + 4 + count] = &accelerometerdisplay_a_self[0]->_lf_x.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port AccelerometerDisplay.a.x to array of intended_tag fields.
            environments[accelerometerdisplay_main]._lf_intended_tag_fields[(0) * 3 + 4 + count] = &accelerometerdisplay_a_self[0]->_lf_x.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add output port AccelerometerDisplay.a.y to array of is_present fields.
            environments[accelerometerdisplay_main].is_present_fields[(0) * 3 + 4 + count] = &accelerometerdisplay_a_self[0]->_lf_y.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port AccelerometerDisplay.a.y to array of intended_tag fields.
            environments[accelerometerdisplay_main]._lf_intended_tag_fields[(0) * 3 + 4 + count] = &accelerometerdisplay_a_self[0]->_lf_y.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add output port AccelerometerDisplay.a.z to array of is_present fields.
            environments[accelerometerdisplay_main].is_present_fields[(0) * 3 + 4 + count] = &accelerometerdisplay_a_self[0]->_lf_z.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port AccelerometerDisplay.a.z to array of intended_tag fields.
            environments[accelerometerdisplay_main]._lf_intended_tag_fields[(0) * 3 + 4 + count] = &accelerometerdisplay_a_self[0]->_lf_z.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance AccelerometerDisplay
    {
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        accelerometerdisplay_main_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
        // index is the OR of level 2 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        accelerometerdisplay_main_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 2);
    
        // Set reaction priorities for ReactorInstance AccelerometerDisplay.a
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            accelerometerdisplay_a_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            accelerometerdisplay_a_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 1);
        }
    
    
        // Set reaction priorities for ReactorInstance AccelerometerDisplay.d
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            accelerometerdisplay_d_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
            // index is the OR of level 3 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            accelerometerdisplay_d_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 3);
        }
    
    }
    

    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&environments[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
 #ifdef FEDERATED_CENTRALIZED
     lf_latest_tag_confirmed(tag_to_send);
 #else
     (void) tag_to_send;
 #endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void lf_terminate_execution(environment_t* env) {
    (void) env;
}
#endif
